service: cfp-api
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-plugin-typescript

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: './tsconfig.json'

package:
  individually: true

provider:
  name: aws
  runtime: nodejs18.x
  deploymentMethod: direct
  stage: prod
  environment:
    SES_AWS_REGION: ${env:SES_AWS_REGION}
    SES_AWS_ACCESS_KEY_ID: ${env:SES_AWS_ACCESS_KEY_ID}
    SES_AWS_SECRET_ACCESS_KEY: ${env:SES_AWS_SECRET_ACCESS_KEY}
    EMAIL: ${env:EMAIL}
    SHEET_ID: ${env:SHEET_ID}
  httpApi:
    cors: true

functions:
  getSubmissions:
    handler: handler.getSubmissions
    events:
      - httpApi:
          method: GET
          path: /submissions/{id}
  postSubmissions:
    handler: handler.postSubmissions
    events:
      - httpApi: 'POST /submissions'
  putSubmissions:
    handler: handler.putSubmissions
    events:
      - httpApi:
          method: PUT
          path: /submissions/{id}
